// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLoading: typeof import('element-plus/es')['ElLoading']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

export { }
